plugins/modules/mso_schema_site_anp_epg_staticport.py
**SUMMARY**
Added ability to configure static port bindings on a fex downstream of a leaf. Fex ports required a different static path.
**ISSUE TYPE**
Feature Pull Request
**ADDITIONAL INFORMATION**
Prior to this addition, the module is unable to configure fex ports because portpath was hard coded to a path specific to leaf ports only. Introducing new, optional fex fields and conditional now allows for fex ports to be configured if desired.
Tested with MSO: 3.0(1i) and ACI: 4.2(4i)
=> Added ability to bind epg to static fex port

tests/integration/targets/mso_label/tasks/main.yml
Fix small issue with cleanup of used objects introduced by the "adding support for login domain" pull request.
Closes #35
=> Remove label with test domain before create it

tests/integration/targets/mso_label/tasks/main.yml, tests/integration/targets/mso_schema_site_anp_epg_domain/tasks/main.yml, tests/integration/targets/mso_schema_site_anp_epg_staticport/tasks/main.yml, tests/integration/targets/mso_schema_template_anp_epg/tasks/main.yml, tests/integration/targets/mso_schema_template_anp_epg_contract/tasks/main.yml, tests/integration/targets/mso_schema_template_bd/tasks/main.yml, tests/integration/targets/mso_schema_template_contract_filter/tasks/main.yml, tests/integration/targets/mso_schema_template_external_epg_contract/tasks/main.yml, tests/integration/targets/mso_schema_template_externalepg/tasks/main.yml, tests/integration/targets/mso_schema_template_vrf_contract/tasks/main.yml, tests/integration/targets/mso_site/tasks/main.yml, tests/integration/targets/mso_tenant/tasks/main.yml
Add Site ID variable named apic_site_id to all tasks
Fix old definition of admin in tenant creation
Add support for "admin" as mso_username
Add mso_login_domain as a variable to tests
This resolves #58 and will allow MSO Engineering to run all the tests directly in their pipeline.
=> Fix all tests to run with user "admin" and add "apic_site_id" as a variable for MSO Engineering pipeline

plugins/modules/mso_tenant_site.py, tests/integration/inventory.networking, tests/integration/targets/mso_tenant_site/aliases, tests/integration/targets/mso_tenant_site/tasks/main.yml
This module has the ability to:
1. Associate cloud sites with a tenant and set its options
2. Associate non-cloud sites with a tenant
=> New module: mso_tenant_site 

plugins/modules/mso_schema_site_vrf_region_cidr.py, plugins/modules/mso_schema_site_vrf_region_cidr_subnet.py, plugins/modules/mso_schema_template_vrf.py, tests/integration/targets/mso_schema_site_anp_epg_domain/tasks/main.yml, tests/integration/targets/mso_schema_site_anp_epg_staticport/tasks/main.yml, tests/integration/targets/mso_schema_site_vrf_region_cidr/aliases, tests/integration/targets/mso_schema_site_vrf_region_cidr/tasks/main.yml, tests/integration/targets/mso_schema_site_vrf_region_cidr_subnet/aliases, tests/integration/targets/mso_schema_site_vrf_region_cidr_subnet/tasks/main.yml, tests/integration/targets/mso_schema_template_anp_epg/tasks/main.yml, tests/integration/targets/mso_schema_template_anp_epg_contract/tasks/main.yml, tests/integration/targets/mso_schema_template_anp_epg_selector/tasks/main.yml, tests/integration/targets/mso_schema_template_bd/tasks/main.yml, tests/integration/targets/mso_schema_template_contract_filter/tasks/main.yml, tests/integration/targets/mso_schema_template_external_epg_contract/tasks/main.yml, tests/integration/targets/mso_schema_template_external_epg_selector/tasks/main.yml, tests/integration/targets/mso_schema_template_externalepg/tasks/main.yml, tests/integration/targets/mso_schema_template_vrf_contract/tasks/main.yml
Fix mso_schema_site_vrf_region_cidr to automatically create VRF and Region if not present at site level
Add support for VGW attribute in mso_schema_site_vrf_region_cidr_subnet
Remove unused regions attribute from mso_schema_template_vrf
Add test for mso_schema_site_vrf_region_cidr module
Add test for mso_schema_site_vrf_region_cidr_subnet module
Resolves #50 
Resolves #66
=> Fix mso_schema_site_vrf_region_cidr and add VGW attribute to mso_schema_site_vrf_region_cidr_subnet

plugins/modules/mso_schema_site_anp_epg_selector.py, tests/integration/targets/mso_schema_site_anp_epg_domain/tasks/main.yml, tests/integration/targets/mso_schema_site_anp_epg_selector/aliases, tests/integration/targets/mso_schema_site_anp_epg_selector/tasks/main.yml
build module 'mso_schema_site_anp_epg_selector' to manage azure/aws endpoint selector for site-level EPG
build test file for module 'mso_schema_site_anp_epg_selector' 
* the test file works in MSO 2.2.4 while fails in MSO 3.0(x) due to API validation changes
resolve #63
=> azure/aws endpoint selector module for EPG (Site level)

plugins/modules/mso_schema_template_anp_epg.py, tests/integration/targets/mso_schema_template_anp_epg/tasks/main.yml, tests/integration/targets/mso_schema_template_external_epg/tasks/main.yml, tests/integration/targets/mso_schema_template_vrf/tasks/main.yml
Fix API error when pushing EPG with existing contracts.
Add test to mso_schema_template_vrf, mso_schema_template_external_epg and mso_schema_template_anp_epg to check for API error when pushing changes to object with existing contract.
Add missing tests for VRF settings and changing those settings.
Resolves #82
=> Fix API error when pushing back EPG with existing contract and add tests

plugins/module_utils/mso.py, plugins/modules/mso_backup.py, tests/integration/targets/mso_backup/aliases, tests/integration/targets/mso_backup/tasks/main.yml
Creates, Deletes and Queries backups
=> new module feature-backup

plugins/module_utils/mso.py, plugins/modules/mso_schema_template_migrate.py, tests/integration/targets/mso_schema_template_migrate/aliases, tests/integration/targets/mso_schema_template_migrate/tasks/main.yml
The issue #89 is solved by creating a new module to support the migration of Bridge Domains (BDs) and End Point Groups (EPGs) between templates in Schema.
=> [mso_schema_template_migrate ] solves migration of BDs and EPGs across templates by creating new module - Object migration solves issue #89

plugins/modules/mso_schema_site_vrf_region.py
Fixed module name in example documentation to the correct one: mso_schema_site_vrf_region
=> [mso_schema_site_vrf_region] Fixed modul names to corresponding module. fixes #130

plugins/modules/mso_schema_site_vrf_region_cidr_subnet.py, tests/integration/targets/mso_schema_site_vrf_region_cidr_subnet/tasks/main.yml
Fix issue on mso_schema_site_vrf_region_cidr_subnet to allow an AWS subnet to be used for a TGW Attachment (Hub Network).
Add hub_network alias to vgw to be clearer for AWS use cases.
Add test case to check that the vgw/hub_network attribute also work on AWS when Hub Network is configured.
Resolves #126
=> Fix issue on mso_schema_site_vrf_region_cidr_subnet to allow an AWS subnet to be used for a TGW Attachment (Hub Network).

plugins/modules/mso_schema_template_bd.py, tests/integration/targets/mso_schema_template_bd/tasks/main.yml
Added the following options to [mso_schema_template_bd] available in mso 3.1 -
Unknown multicast flooding (OMF)
Multi dest flooding
ARP flooding (with dependencies on inter site BUM, L2 unicast flooding)
BD/vMAC
IPV6 unknown multicast flooding
Updated test file accordingly
=> [mso_schema_template_bd]Added new options to template bd and updated its test file fixes #140

plugins/module_utils/mso.py
Cisco MSO 3.2 in combination with Nexus Dashboard responds with a 200 OK instead of 201 OK. This fixes the authentication failed error from Ansible with MSO 3.2.
=> Fix Ansible auth issue with ND/MSO 3.2

plugins/modules/mso_schema_site_external_epg.py, tests/integration/targets/mso_schema_site_external_epg/tasks/main.yml
solves #383 
Associating L3Out created in different templates is only possible in site external EPGs created in NDO version < 4.0.
=> [minor_changes] Added L3Out Argument at site external EPG module

plugins/module_utils/utils.py
Note:
Used the same function to test the code with this PR: https://github.com/CiscoDevNet/ansible-mso/pull/563
=> Added append_update_ops_data to handle the latest ndo module update operations (DCNE-245)

plugins/modules/ndo_mcp_global_policy.py, tests/integration/targets/ndo_mcp_global_policy/aliases, tests/integration/targets/ndo_mcp_global_policy/tasks/main.yml
Fixed #451 
This MCP Global policy module is based on a 1:1 relationship with Fabric Policy templates.
A decision was made to keep this configuration in a separate module instead of adding it to `ndo_template`.
=> [minor_change] Added ndo_mcp_global_policy for fabric policy global MCP configuration (DCNE-70)

plugins/module_utils/mso.py, plugins/module_utils/template.py, plugins/modules/ndo_port_channel_interface.py, tests/integration/targets/ndo_port_channel_interface/aliases, tests/integration/targets/ndo_port_channel_interface/tasks/main.yml
resolves #466
New Modules Added:
- ndo_port_channel_interface
=> Add a new module to manage Port Channel Interfaces in Fabric Resource Policies Template. (DCNE-52)

plugins/module_utils/schema.py, plugins/modules/mso_schema_template_anp_epg_annotation.py, tests/integration/targets/mso_schema_template_anp_epg_annotation/aliases, tests/integration/targets/mso_schema_template_anp_epg_annotation/tasks/main.yml
=> Added mso_schema_template_anp_epg_annotation to manage EPG annotations (DCNE-60)

plugins/module_utils/template.py, plugins/modules/ndo_physical_interface.py, tests/integration/targets/ndo_physical_interface/aliases, tests/integration/targets/ndo_physical_interface/tasks/main.yml
(object: interfaceProfiles)
solves #392 
it required ndo_interface_seeting module #540
=> [minor_changes] Adding new module for physical interface (DCNE-50)

plugins/modules/mso_schema_site_anp_epg_staticport.py, tests/integration/targets/mso_schema_site_anp_epg_staticport/tasks/main.yml
- Updated the code to make the `vlan` parameter optional when the `state` is `absent`.
- This change ensures that the `vlan` parameter is not required when the state is set to `absent`, preventing potential errors or unnecessary requirements.
- Added appropriate checks to handle the absence of the `vlan` parameter gracefully.
* `mso_schema_site_anp_epg_staticport`
* Tested with NDO 4.1
* Tested with APIC 5.2
* cisco.mso 2.9.0
* Resolves #607
=> [EPG Static Port] Make VLAN parameter optional when the state is absent (DCNE-300)

plugins/modules/ndo_virtual_port_channel_interface.py, tests/integration/targets/ndo_virtual_port_channel_interface/aliases, tests/integration/targets/ndo_virtual_port_channel_interface/tasks/main.yml
resolves #467 
New Modules Added:
- ndo_virtual_port_channel_interface
=> Add a new module to manage Virtual Port Channel Interfaces in Fabric Resource Policies Template. (DCNE-53)

plugins/module_utils/mso.py, plugins/module_utils/template.py, plugins/module_utils/utils.py, plugins/modules/ndo_dhcp_option_policy.py, plugins/modules/ndo_dhcp_relay_policy.py, plugins/modules/ndo_interface_setting.py, plugins/modules/ndo_l3_domain.py, plugins/modules/ndo_l3out_template.py, plugins/modules/ndo_physical_domain.py, plugins/modules/ndo_port_channel_interface.py, plugins/modules/ndo_route_map_policy_multicast.py, plugins/modules/ndo_synce_interface_policy.py, plugins/modules/ndo_template.py, plugins/modules/ndo_vlan_pool.py, tests/integration/targets/ndo_dhcp_relay_policy/tasks/main.yml, tests/integration/targets/ndo_interface_setting/tasks/main.yml, tests/integration/targets/ndo_l3_domain/tasks/main.yml, tests/integration/targets/ndo_l3out_template/tasks/main.yml, tests/integration/targets/ndo_physical_domain/tasks/main.yml, tests/integration/targets/ndo_port_channel_interface/tasks/main.yml, tests/integration/targets/ndo_template/tasks/main.yml, tests/integration/targets/ndo_vlan_pool/tasks/main.yml
Note:
Fixed the below NDO modules:
- ndo_synce_interface_policy
- ndo_vlan_pool
- ndo_dhcp_option_policy
- ndo_dhcp_relay_policy
- ndo_l3_domain
- ndo_physical_domain
- ndo_route_map_policy_multicast
=> [minor_change] Replaced the ndo modules current value with actual API response value (DCNE-185)

plugins/module_utils/template.py, plugins/modules/ndo_pod_profile.py, tests/integration/targets/ndo_pod_profile/aliases, tests/integration/targets/ndo_pod_profile/tasks/main.yml
=> [minor_change] Add module ndo_pod_profile for pod profiles in fabric resource templates (DCNE-141)
