CiscoDevNet/ansible-mso

plugins/module_utils/mso.py
plugins/modules/mso_role.py
plugins/modules/mso_schema_site_anp_epg_subnet.py
plugins/modules/mso_schema_site_bd_subnet.py
plugins/modules/mso_schema_template_anp_epg.py
plugins/modules/mso_schema_template_anp_epg_subnet.py
plugins/modules/mso_schema_template_bd.py
plugins/modules/mso_schema_template_bd_subnet.py
tests/integration/targets/mso_schema_template_bd/aliases
tests/integration/targets/mso_schema_template_bd/tasks/main.yml
tests/integration/targets/mso_site/tasks/main.yml
tests/integration/targets/mso_tenant/tasks/main.yml

Update mso_schema_template_bd.py example for BD in another schema.
Add full integration test for mso_schema_template_db
Add a few fixes found during mso_schema_template_bd integration tests and debug tools
Added DHCP relay options and querier to BDs
Add aliases to fix backward support of permissions in mso_role module
Thanks to the PR of Justin Haef and David Nibbe.
Resolves #5
Resolves #4 
Resolves #1  
Resolves ansible/ansible#64737
Resolves ansible/ansible#67877
Resolves ansible/ansible#65341

Add integration tests, DHCP relay and IGMP querier to mso_schema_template_bd

---

.github/workflows/ansible-test.yml
tests/integration/inventory.networking
tests/integration/targets/mso_schema_template_bd/tasks/main.yml
tests/integration/targets/mso_site/tasks/main.yml
tests/integration/targets/mso_tenant/tasks/main.yml
tests/integration/targets/mso_user/tasks/main.yml

Move password for CI/CD pipeline into Github secrets.
Add some tests to existing test cases.

Fix CI/CD pipeline to avoid concurrent runs.

---

plugins/module_utils/mso.py
plugins/modules/mso_schema_template_contract_filter.py
tests/integration/targets/mso_schema_template_contract_filter/tasks/main.yml

add test file for module mso_schema_template_contract_filter
fix issue 'mso_schema_template_contract_filter does not work for vrf scope #17'
add function to transform filterRef format
Resolves #17

fix issue 'mso_schema_template_contract_filter does not work for vrf scope #17'

---

plugins/doc_fragments/modules.py
plugins/module_utils/mso.py
plugins/modules/mso_schema_template_contract_filter.py
tests/integration/targets/mso_label/tasks/main.yml

adding support for login domain

---

plugins/module_utils/mso.py
plugins/modules/mso_tenant.py
tests/integration/targets/mso_tenant/tasks/main.yml

Fix duplicate user issue in tenant module
Add admin user to the associated user list irrespective of this parameter being used
Update tenant test file
Resolve #19

fix duplicate user and update tenant test file

---

galaxy.yml

Bump version to 0.0.6 and update authors.

Bump version to 0.0.6 in preparation for new release

---

plugins/modules/mso_schema_site_anp_epg_staticport.py
tests/integration/targets/mso_schema_site_anp_epg_staticport/tasks/main.yml

1. Addition of Direct Port Channel option and its attribute Micro Segment VLAN
2. Addition of default values for deployment immediacy and mode 
3. Updated Test File

New functionality and modifications for mso_schema_site_anp_epg_staticport

---

plugins/module_utils/mso.py
plugins/modules/mso_schema_template_externalepg.py
tests/integration/targets/mso_schema_template_externalepg/aliases
tests/integration/targets/mso_schema_template_externalepg/tasks/main.yml

Add l3 out and preferred group attribute

---

plugins/modules/mso_schema_template_vrf.py
plugins/modules/mso_schema_template_vrf_contract.py
plugins/modules/mso_schema_vrf_contract.py
tests/integration/targets/mso_schema_template_vrf_contract/aliases
tests/integration/targets/mso_schema_template_vrf_contract/tasks/main.yml

build module 'mso_schema_template_vrf_contract' and its test file
add vzAny attribute in module 'mso_schema_template_vrf'
resolve #41

build new module 'mso_schema_template_vrf_contract' with test file

---

plugins/module_utils/mso.py
plugins/modules/mso_schema_template_anp_epg_selector.py
tests/integration/targets/mso_schema_template_anp_epg_selector/aliases
tests/integration/targets/mso_schema_template_anp_epg_selector/tasks/main.yml

build a new module "mso_schema_template_anp_epg_selector" to manage selectors in EPG
build a test file for this new module
resolve #21

azure/aws endpoint selector module for EPG (Template level)

---

plugins/module_utils/mso.py
plugins/modules/mso_schema_template_external_epg_selector.py
plugins/modules/mso_schema_template_externalepg.py
tests/integration/targets/mso_schema_template_external_epg_selector/aliases
tests/integration/targets/mso_schema_template_external_epg_selector/tasks/main.yml
tests/integration/targets/mso_schema_template_externalepg/tasks/main.yml

Modified: mso_schema_template_externalepg
- Can associate ANP with the External EPG
New module: mso_schema_template_external_epg_selector
- Adds selectors to External EPGs

Modified External EPG module and new Selector module

---

plugins/module_utils/mso.py
plugins/modules/mso_schema_site_external_epg_selector.py
plugins/modules/mso_schema_template_contract_filter.py
tests/integration/targets/mso_schema_site_external_epg_selector/aliases
tests/integration/targets/mso_schema_site_external_epg_selector/tasks/main.yml
tests/integration/targets/mso_schema_template_contract_filter/tasks/main.yml
tests/integration/targets/mso_schema_template_external_epg_selector/tasks/main.yml
tests/integration/targets/mso_schema_template_vrf/aliases
tests/integration/targets/mso_schema_template_vrf/tasks/main.yml

1. Reviewed mso_schema_site_external_epg_selector module and its test file
2. Enhancement for mso_schema_template_contract_filter. Added policy_compression
3. mso_schema_template_vrf test file
Resolves #40 
Resolves #61 
Resolves #64

Enhancements, tests and a new module

---

plugins/modules/mso_user.py
tests/integration/targets/mso_user/tasks/main.yml

- add option 'inactive' for account_status in mso_user
- add test tasks to inactive or active mso user
resolve #44

Add support for making user inactive

---

plugins/modules/mso_schema_site_bd.py
tests/integration/targets/mso_schema_site_bd/aliases
tests/integration/targets/mso_schema_site_bd/tasks/main.yml

build test file for module 'mso_schema_site_bd'
resolve #49

Add support for Host Route

---

galaxy.yml

Bump version to v0.0.7

---

plugins/modules/mso_user.py
tests/integration/targets/mso_user/tasks/main.yml

1. Updated module to capture and fail creation of a user with no password.
2. Updated test file to include read only case.
Resolves #45

mso_user modified

---

plugins/modules/mso_schema_site_bd_subnet.py
plugins/modules/mso_schema_template_bd.py
tests/integration/targets/mso_schema_site_bd_subnet/aliases
tests/integration/targets/mso_schema_site_bd_subnet/tasks/main.yml

- fix issue of failing to deploy site bd subnets to APIC
- implement test file for mso_schema_site_bd_subnet module
resolve #93

[mso_schema_site_bd_subnet] fix issue of failing to deploy site bd subnets to APIC

---

tests/integration/targets/mso_tenant/tasks/main.yml

- add another 2 tasks to test the issues #92 and #102 
-  make sure that these issues are already fixed in current version of code
resolve #92 
resolve #102

[mso_tenant] add two more tasks in testing file to cover the issues #92 and #102

---

plugins/modules/mso_schema_template_l3out.py
plugins/modules/mso_user.py

fix some examples in mso_user module and mso_schema_template_l3out module

fix examples in the  documentation

---

CHANGELOG.rst
changelogs/changelog.yaml
galaxy.yml
plugins/doc_fragments/modules.py
plugins/module_utils/mso.py

- Remove author emails due to length restriction
- Add env_fallback for mso_argument_spec params
- Bump module to v1.0.1 and add changelog

Add ENV fallback for MSO Arguments Specs and Bump to v1.0.1

---

plugins/modules/mso_schema_template_anp.py
tests/integration/targets/mso_schema_template_anp/aliases
tests/integration/targets/mso_schema_template_anp/tasks/main.yml

- Fix idempotency issue for mso_schema_template_anp
- Add test file for mso_schema_template_anp

fix mso_schema_template_anp idempotency issue

---

plugins/modules/mso_schema.py
tests/integration/targets/mso_schema/aliases
tests/integration/targets/mso_schema/tasks/main.yml

resolve #123 
- Remove 'present' state from mso_schema
- Fix documentation for mso_schema
- Add test file for mso_schema

remove 'present' from mso_schema

---

plugins/module_utils/mso.py
plugins/modules/mso_rest.py
tests/integration/targets/mso_rest/aliases
tests/integration/targets/mso_rest/tasks/error_handling.yml
tests/integration/targets/mso_rest/tasks/json_inline.yml
tests/integration/targets/mso_rest/tasks/json_string.yml
tests/integration/targets/mso_rest/tasks/json_template.yml
tests/integration/targets/mso_rest/tasks/main.yml
tests/integration/targets/mso_rest/tasks/tenant.json.j2
tests/integration/targets/mso_rest/tasks/yaml_inline.yml
tests/integration/targets/mso_rest/tasks/yaml_string.yml

Resolves issue #112 by creation of new module to execute REST API methods for ansible-mso.

[mso_rest] Adding mso_rest module to execute REST APIs fixes #112

---

plugins/modules/mso_schema_site_vrf_region.py
tests/integration/targets/mso_schema_site_vrf_region/aliases
tests/integration/targets/mso_schema_site_vrf_region/tasks/main.yml

- build test file for mso_schema_site_vrf_region
- fix crash issue when trying to use irrelevant site/template
- add notes in document
resolve #138

Fix mso_schema_site_vrf_region

---

plugins/module_utils/mso.py
plugins/modules/mso_dhcp_option_policy.py
plugins/modules/mso_dhcp_option_policy_option.py
plugins/modules/mso_dhcp_relay_policy.py
plugins/modules/mso_dhcp_relay_policy_provider.py
plugins/modules/mso_schema_template_bd.py
tests/integration/targets/mso_dhcp_option_policy/aliases
tests/integration/targets/mso_dhcp_option_policy/tasks/main.yaml
tests/integration/targets/mso_dhcp_option_policy_option/aliases
tests/integration/targets/mso_dhcp_option_policy_option/tasks/main.yaml
tests/integration/targets/mso_dhcp_relay_policy/aliases
tests/integration/targets/mso_dhcp_relay_policy/tasks/main.yaml
tests/integration/targets/mso_dhcp_relay_policy_provider/aliases
tests/integration/targets/mso_dhcp_relay_policy_provider/tasks/main.yaml
tests/integration/targets/mso_rest/tasks/json_inline.yml
tests/integration/targets/mso_schema/tasks/main.yml

Added support to create/delete/modify DHCP Relay Policies and DHCP Relay Policies Providers
State 'Query' still to be discussed
Please reach out to me internally for further questions (CCO: jgomezve)

MSO DHCP Policies

---

plugins/module_utils/mso.py
plugins/modules/mso_schema_template_bd_subnet.py
tests/integration/targets/mso_schema_template_bd_subnet/aliases
tests/integration/targets/mso_schema_template_bd_subnet/tasks/main.yml

New test file for [mso_schema_template_bd_subnet]
Added option virtual_ip for version 3.1

[mso_schema_template_bd_subnet]Test file for template_bd_subnet and new option for virtual_ip module fixes #141

---

plugins/modules/mso_schema_site_bd_subnet.py
tests/integration/targets/mso_schema_site_bd_subnet/tasks/main.yml

is_virtual_ip is added as an option to this module for mso version 3.1

[mso_schema_site_bd_subnet] Added attribute virtual_ip

---

plugins/module_utils/mso.py
plugins/modules/mso_backup.py
tests/integration/inventory.networking
tests/integration/network-integration.requirements.txt
tests/integration/targets/mso_backup/tasks/main.yml
tests/integration/targets/mso_tenant_site/tasks/main.yml
tests/sanity/requirements.txt

Capabilities:
import (upload) from remote location and from file.
Rollback to a backup
download to local file
move backup from local to remote

[mso_backup] Add other capabilities to existing backup module fixes #84

---

requirements.txt

This PR is a follow up to an email sent to the maintainers of this certified collection notifying them of a few new changes that will be needed for the next Ansible Automation Platform release. Contained in this PR is an example python requirements file built specifically for your collection. You can elect to merge this as is and edit as needed or close the PR and use it as an example to base your own commit off of. if you have any questions about why this PR was sent or confused about its necessity, please don't hesitate to ask in the comments here or email us at ansiblepartners@redhat.com

Add requirements.txt File

---

plugins/modules/mso_schema.py

[mso_schema] Made changes in the documentation of mso_schema module issue #161

---

.github/workflows/ansible-test.yml
plugins/module_utils/mso.py
plugins/modules/mso_schema_site_external_epg.py
plugins/modules/mso_schema_site_l3out.py
plugins/modules/mso_schema_template_l3out.py
tests/integration/targets/mso_dhcp_relay_policy_provider/tasks/main.yaml
tests/integration/targets/mso_schema_site_external_epg/aliases
tests/integration/targets/mso_schema_site_external_epg/tasks/main.yml
tests/integration/targets/mso_schema_site_external_epg_selector/tasks/main.yml
tests/integration/targets/mso_schema_site_l3out/aliases
tests/integration/targets/mso_schema_site_l3out/tasks/main.yml
tests/integration/targets/mso_schema_template_external_epg/tasks/main.yml
tests/integration/targets/mso_schema_template_external_epg_selector/tasks/main.yml
tests/integration/targets/mso_schema_template_l3out/aliases
tests/integration/targets/mso_schema_template_l3out/tasks/main.yml

Resolves issue #119 by adding new module (mso_schema_site_external_epg) to add external EPGs to non-cloud sites.

[mso_schema_site_external_epg] Adding new mso_schema_site_external_epg module for non-cloud sites. Fixes #119

---

.github/workflows/ansible-test.yml
plugins/module_utils/mso.py
plugins/modules/mso_schema_template_anp_epg.py
plugins/modules/mso_schema_template_bd.py
plugins/modules/mso_schema_template_bd_dhcp_policy.py
tests/integration/targets/mso_dhcp_option_policy/tasks/main.yaml
tests/integration/targets/mso_dhcp_option_policy_option/tasks/main.yaml
tests/integration/targets/mso_dhcp_relay_policy/tasks/main.yaml
tests/integration/targets/mso_dhcp_relay_policy_provider/tasks/main.yaml
tests/integration/targets/mso_schema_template_bd/tasks/main.yml
tests/integration/targets/mso_schema_template_bd_dhcp_policy/aliases
tests/integration/targets/mso_schema_template_bd_dhcp_policy/tasks/main.yml

Ability to add multiple DHCP policies

DHCP labels for version 3.1.1h and above

---

tests/integration/targets/mso_schema_template/tasks/main.yml
tests/integration/targets/mso_schema_template_anp/tasks/main.yml

Test for same template names in different schemas and tenants

---

plugins/module_utils/mso.py
plugins/modules/mso_schema_clone.py
plugins/modules/mso_schema_template_clone.py
tests/integration/targets/mso_schema_clone/aliases
tests/integration/targets/mso_schema_clone/tasks/main.yml
tests/integration/targets/mso_schema_template_clone/aliases
tests/integration/targets/mso_schema_template_clone/tasks/main.yml
tests/integration/targets/mso_schema_template_external_epg/tasks/main.yml

[mso_schema_clone] Supports cloning the schema issue #190

---

plugins/modules/mso_schema_validate.py
tests/integration/targets/mso_schema_validate/aliases
tests/integration/targets/mso_schema_validate/tasks/main.yml

[mso_schema_validate] Added validate module to support MSO version >= 3.3 #197

---

plugins/modules/mso_schema_site_bd_subnet.py
plugins/modules/mso_schema_template_bd_subnet.py

[mso_schema_template_bd_subnet ]Changed the default value representation for scope parameter. issue #187

---

plugins/modules/mso_schema_template_anp_epg.py
tests/integration/targets/mso_schema_template_anp_epg/tasks/main.yml

[mso_schema_template_anp_epg] Added description and QoS level parameter to ANP EPG. Fixes issue #195

---

plugins/modules/mso_schema_site_anp.py
plugins/modules/mso_schema_site_anp_epg.py
plugins/modules/mso_schema_site_vrf_region_cidr_subnet.py
tests/integration/targets/mso_label/tasks/main.yml
tests/integration/targets/mso_schema_site_anp/aliases
tests/integration/targets/mso_schema_site_anp/tasks/main.yml
tests/integration/targets/mso_schema_site_anp_epg/aliases
tests/integration/targets/mso_schema_site_anp_epg/tasks/main.yml
tests/integration/targets/mso_schema_site_vrf_region_cidr_subnet/tasks/main.yml

[mso_schema_site_vrf_region_cidr_subnet] Added private Link Label parameter on site vrf region cidr subnet

---

plugins/modules/mso_schema_site_vrf_region.py
plugins/modules/mso_schema_site_vrf_region_cidr_subnet.py
tests/integration/targets/mso_schema_site_vrf_region/tasks/main.yml
tests/integration/targets/mso_schema_site_vrf_region_cidr_subnet/tasks/main.yml

Added underlay context profile under mso_schema_site_vrf_region.py modules
fixes #201
fixes #202

[mso_schema_site_vrf_region] Added underlay context profile parameters solves issue #201 #202

---

plugins/doc_fragments/modules.py
plugins/httpapi/mso.py
plugins/module_utils/mso.py
tests/integration/inventory.networking
tests/integration/targets/mso_version/tasks/main.yml

- Fix MSO HTTPAPI plugin
- Remove required=True for use_proxy&use_ssl&validate_certs
- Add test task for MSO HTTPAPI plugin
- Update inventory to apply MSO HTTPAPI

Fix mso httpapi

---

plugins/modules/mso_schema_site_anp.py
tests/integration/targets/mso_schema_site_anp/tasks/main.yml

With this PR, ANP shows no change when added at site level again.

Changes to anpref

---

plugins/doc_fragments/modules.py

Update documentation for use_ssl

---

plugins/modules/mso_schema_site_anp.py
tests/integration/targets/mso_schema_site_anp/tasks/main.yml
tests/integration/targets/mso_schema_site_anp_epg/tasks/main.yml

[bugfix] Add function to site_anp for idempotency check (depends on  PR #233)

---

plugins/doc_fragments/modules.py

[bugfix] remove mso_guide from notes

---

plugins/modules/mso_schema_site_bd_subnet.py
tests/integration/targets/mso_schema_site_bd_subnet/tasks/main.yml

Add primary attribute to the site level module to match functionality in the template level module.

Add primary attribute to mso_schema_site_bd_subnet to match mso_schema_template_bd_subnet

---

plugins/modules/mso_backup.py
plugins/modules/mso_backup_schedule.py
tests/integration/targets/mso_backup_schedule/aliases
tests/integration/targets/mso_backup_schedule/tasks/main.yml

Note:
Added backup scheduler functionality
Issue: #85

[feature]: initial mso backup schedule

---

plugins/module_utils/mso.py
tests/integration/targets/mso_schema_site/tasks/main.yml

Note:
Added patch_operation attribute to the mso module to print the full PATCH operations when output_level is debug and the invocation method is PATCH.

Added patch_operation attribute to the mso module utility 

---

plugins/modules/mso_schema_template_bd.py
tests/integration/targets/mso_schema_template_bd/tasks/main.yml

[fix] schema template bd create with false

---

plugins/module_utils/mso.py
plugins/modules/mso_schema_site_anp.py
plugins/modules/mso_schema_site_anp_epg.py
tests/integration/targets/mso_schema_site_anp/tasks/main.yml
tests/integration/targets/mso_schema_site_anp_epg/tasks/main.yml

[minor_change] deploymentImmediacy mso 400 error workaround

---

plugins/module_utils/constants.py
plugins/module_utils/mso.py
plugins/modules/mso_tenant.py
tests/integration/targets/mso_tenant/tasks/main.yml

Note:
Added additional validations to the mso_tenant module and implemented logic to delete the tenant from MSO and Sites.

Added additional validations and implemented logic to delete the tenant from MSO and Sites

---

plugins/module_utils/schema.py
plugins/modules/mso_schema_site_bd_subnet.py
tests/integration/targets/mso_schema_site_bd_subnet/tasks/main.yml

[minor_change] create site bd from site bd subnet module

---

plugins/modules/mso_schema_template_contract_filter.py
tests/integration/targets/mso_schema_template_contract_filter/tasks/main.yml

[minor change] path bug fix

---

plugins/modules/mso_schema_site_bd_l3out.py
tests/integration/targets/mso_schema_site_bd_l3out/tasks/main.yml

[minor_change] l3out support from different template or schema

---

plugins/modules/mso_backup_schedule.py
tests/integration/targets/mso_backup_schedule/tasks/main.yml

[bugfix] change module to support python2.7

---

plugins/modules/mso_schema_site_anp_epg_bulk_staticport.py
tests/integration/targets/mso_schema_site_anp_epg_bulk_staticport/tasks/main.yml

Added static_ports arguments to required_if section in bulk static port model.

[minor_changes] Added static_ports arguments to required_if

---

plugins/module_utils/mso.py
plugins/modules/mso_schema_site_anp_epg_bulk_staticport.py
tests/integration/targets/mso_schema_site_anp_epg_bulk_staticport/tasks/main.yml

Adding same paths for different leaf validated in mso_schema_site_anp_epg_bulk_staticport module. Examples attached.

[minor_changes] Bulk Static Port path validation condition changed.

---

plugins/modules/mso_schema_template_vrf.py
tests/integration/targets/mso_schema_template_vrf/tasks/main.yml

Added ip_data_plane_learning and preferred_group arguments to schema_template_vrf resource

[minor_changes] Added additional arguments to schema_template_vrf resource.

---

plugins/module_utils/constants.py
plugins/module_utils/mso.py
plugins/modules/mso_backup.py
tests/integration/targets/mso_backup/tasks/main.yml

Note:
Added NDO backup support to the mso_backup module

Added NDO backup support

---

plugins/module_utils/constants.py
plugins/module_utils/schema.py
plugins/modules/mso_schema_template_anp_epg_useg_attribute.py
tests/integration/targets/mso_schema_template_anp_epg_useg_attribute/aliases
tests/integration/targets/mso_schema_template_anp_epg_useg_attribute/tasks/main.yml

Note:
Added a new module to manage EPG uSeg attributes.

Added a new module to manage EPG uSeg attribute

---

plugins/module_utils/constants.py
plugins/module_utils/schema.py
plugins/modules/mso_schema_site_anp_epg_useg_attribute.py
tests/integration/targets/mso_schema_site_anp_epg_useg_attribute/aliases
tests/integration/targets/mso_schema_site_anp_epg_useg_attribute/tasks/main.yml

Note:
mso_schema_site_anp_epg_useg_attribute.py - is used to manage the site-level EPG uSeg Attributes.

Added a new module to manage Site uSeg Attrs - mso_schema_site_anp_epg_useg_attribute.py

---

plugins/doc_fragments/modules.py
plugins/httpapi/mso.py
plugins/module_utils/mso.py
tests/integration/inventory.networking
tests/integration/targets/mso_version/tasks/connection.yml
tests/integration/targets/mso_version/tasks/main.yml

312 global domain login

---

.github/workflows/ansible-test.yml
plugins/module_utils/mso.py
plugins/modules/mso_tenant.py
tests/integration/targets/mso_tenant/tasks/main.yml

resolves conflicts with same name in remote and local user, by giving precendence to local_users.
solves #163

[minor_changes] Added functionality to resolves remote user 

---

plugins/modules/mso_schema.py
plugins/modules/mso_schema_template.py
tests/integration/inventory.networking
tests/integration/targets/mso_schema/tasks/main.yml
tests/integration/targets/mso_schema_template/tasks/main.yml

380 empty mso schema

---

plugins/modules/mso_schema_site_anp_epg_useg_attribute.py
plugins/modules/mso_schema_template_anp_epg_useg_attribute.py
tests/integration/targets/mso_schema_site_anp_epg_useg_attribute/tasks/main.yml
tests/integration/targets/mso_schema_template_anp_epg_useg_attribute/tasks/main.yml

Note:
Fixed the useg_subnet logic and added additional validation tasks

Fixed the useg_subnet logic in the mso_schema_template_anp_epg_useg_attribute.py module

---

plugins/module_utils/constants.py
plugins/module_utils/mso.py
plugins/modules/mso_schema_site_service_graph.py
plugins/modules/mso_schema_template_service_graph.py
tests/integration/targets/mso_schema_site_service_graph/tasks/l4_l7_devices.yml
tests/integration/targets/mso_schema_site_service_graph/tasks/main.yml
tests/integration/targets/mso_schema_template_service_graph/tasks/main.yml

Note:
Added Azure Cloud CNC support to the mso_schema_site_service_graph module and fixed mso_schema_template_service_graph module.

Added Azure Cloud CNC support to the mso_schema_site_service_graph module

---

plugins/module_utils/mso.py
plugins/module_utils/schema.py
plugins/modules/mso_schema_site_contract_service_graph.py
plugins/modules/mso_schema_site_service_graph.py
tests/integration/targets/mso_schema_site_contract_service_graph/aliases
tests/integration/targets/mso_schema_site_contract_service_graph/tasks/main.yml
tests/integration/targets/mso_schema_site_service_graph/tasks/main.yml

Note:
Also fixed schema template and site service graph modules.

Added mso_schema_site_contract_service_graph module to manage site contract service graph

---

plugins/module_utils/schema.py
plugins/modules/mso_schema_site_contract_service_graph.py
tests/integration/targets/mso_schema_site_contract_service_graph/tasks/l4_l7_devices.yml
tests/integration/targets/mso_schema_site_contract_service_graph/tasks/main.yml

Note:
Added Azure cloud site support for the mso_schema_site_contract_service_graph.py module
Also, replaced the main.yml file values with variables.

Added Azure cloud site support for the mso_schema_site_contract_service_graph.py module

---

plugins/module_utils/template.py
plugins/modules/ndo_route_map_policy_multicast.py
tests/integration/targets/ndo_route_map_policy_multicast/aliases
tests/integration/targets/ndo_route_map_policy_multicast/tasks/main.yml

needed for #426 and https://github.com/CiscoDevNet/ansible-mso/issues/425

Tenant policy multicast route map policy

---

plugins/modules/mso_schema_template_bd.py
tests/integration/targets/mso_schema_template_bd/tasks/main.yml

426 template bd route map filter

---

plugins/modules/mso_dhcp_option_policy.py
plugins/modules/mso_dhcp_option_policy_option.py
plugins/modules/mso_dhcp_relay_policy.py
plugins/modules/mso_dhcp_relay_policy_provider.py
plugins/modules/ndo_dhcp_option_policy.py
plugins/modules/ndo_dhcp_relay_policy.py
tests/integration/targets/ndo_dhcp_option_policy/aliases
tests/integration/targets/ndo_dhcp_option_policy/tasks/main.yml
tests/integration/targets/ndo_dhcp_relay_policy/aliases
tests/integration/targets/ndo_dhcp_relay_policy/tasks/main.yml

313 dhcp relay and option

---

plugins/module_utils/template.py
plugins/modules/ndo_l3_domain.py
plugins/modules/ndo_physical_domain.py
tests/integration/targets/ndo_l3_domain/aliases
tests/integration/targets/ndo_l3_domain/tasks/main.yml
tests/integration/targets/ndo_physical_domain/aliases
tests/integration/targets/ndo_physical_domain/tasks/main.yml

439 440 fabic policies l3 and physical domain

---

plugins/modules/mso_schema_template_vrf.py
tests/integration/targets/mso_schema_template_vrf/tasks/main.yml
tests/integration/targets/mso_schema_template_vrf_rp/tasks/main.yml

Has commits from not merged PR #425 which were required for a test case. Might need rebase after that one is merged.

Fix template vrf patch

---

plugins/modules/mso_dhcp_option_policy_option.py

[ignore] Remove aliases in documentation of attribute dhcp_option_policy in mso_dhcp_option_policy_option module

---

plugins/module_utils/schema.py
plugins/modules/mso_schema_template_bd_dhcp_policy.py
plugins/modules/ndo_schema_template_bd_dhcp_policy.py
tests/integration/targets/ndo_schema_template_bd_dhcp_policy/aliases
tests/integration/targets/ndo_schema_template_bd_dhcp_policy/tasks/main.yml

with ndo_schema_template_bd_dhcp_policy
fixes #495

[minor_change] Add support for Template BD DHCP Policy configuration in ndo version 4+ with ndo_schema_template_bd_dhcp_policy

---

plugins/modules/mso_schema_template_anp_epg_contract.py
tests/integration/targets/mso_schema_template_anp_epg_contract/tasks/main.yml

Small proposed fix for issue #523
DCNE-166

Updated mso.mso_schema_template_anp_epg_contract query logic

---

plugins/module_utils/constants.py
plugins/modules/ndo_synce_interface_policy.py
tests/integration/targets/ndo_synce_interface_policy/aliases
tests/integration/targets/ndo_synce_interface_policy/tasks/main.yml

(syncEthIntfPolicies object) 
part of issue #456
DCNE-129

[minor_changes] Added new module for syncE interface policy 

---

plugins/module_utils/constants.py
plugins/module_utils/template.py
plugins/module_utils/utils.py
plugins/modules/ndo_l3out_template.py
tests/integration/targets/ndo_l3out_template/aliases
tests/integration/targets/ndo_l3out_template/tasks/main.yml

Added ndo_l3out_template module and test file (DCNE-56)

---

README.md

Readme should match this template https://access.redhat.com/articles/7068606

[bug_fix] Updated README to match RedHat's ansible collection template (DCNE-200)

---

plugins/modules/mso_schema_template_external_epg_subnet.py
tests/integration/targets/mso_schema_template_external_epg_subnet/tasks/main.yml

[minor_change] Add support for name attribute in mso_schema_template_external_epg_subnet module (DCNE-59)

---

plugins/module_utils/constants.py
plugins/modules/ndo_tenant_mld_snooping_policy.py
tests/integration/targets/ndo_tenant_mld_snooping_policy/aliases
tests/integration/targets/ndo_tenant_mld_snooping_policy/tasks/main.yml

[minor_change] Add module ndo_tenant_mld_snooping_policy for tenant mld snooping configuration (DCNE-129)

---

plugins/modules/ndo_tenant_igmp_snooping_policy.py
tests/integration/targets/ndo_tenant_igmp_snooping_policy/aliases
tests/integration/targets/ndo_tenant_igmp_snooping_policy/tasks/main.yml

IGMP Snooping policy in Tenant Policy Templates. It is part of schema_template_bd module.
solves #455

[minor_changes] Adding new module for IGMP Snooping policy (DCNE-130)

---

plugins/module_utils/mso.py
plugins/module_utils/schema.py
plugins/module_utils/template.py
plugins/modules/ndo_ipsla_monitoring_policy.py
plugins/modules/ndo_ipsla_track_list.py
tests/integration/targets/ndo_ipsla_track_list/aliases
tests/integration/targets/ndo_ipsla_track_list/tasks/main.yml

[minor_change] Added new module for IPSLA Track Lists (DCNE-134)

---

plugins/module_utils/constants.py
plugins/module_utils/utils.py
plugins/modules/ndo_qos_class_policy.py
tests/integration/targets/ndo_qos_class_policy/aliases
tests/integration/targets/ndo_qos_class_policy/tasks/main.yml

Add QoS Class Policy as a new module (DCNE-73)

---

plugins/module_utils/mso.py

Added new API endpoint to query local and remote users in the mso.py module (DCNE-377)

---

.github/workflows/ansible-test.yml

[minor_change] Added testing support for Ansible Core 2.19 (DCNE-397)

---

plugins/module_utils/template.py
plugins/module_utils/templates.py
plugins/modules/ndo_l3out_node_static_route.py
tests/integration/targets/ndo_l3out_node_static_route/aliases
tests/integration/targets/ndo_l3out_node_static_route/tasks/main.yml

[minor_change] Add module ndo_l3out_node_static_route to configure static routes for nodes in l3out templates (DCNE-439)

---

plugins/module_utils/mso.py
plugins/module_utils/template.py
plugins/modules/ndo_l3out_routed_interface.py
plugins/modules/ndo_l3out_routed_sub_interface.py
plugins/modules/ndo_l3out_svi_interface.py
tests/integration/targets/ndo_l3out_routed_interface/tasks/main.yml
tests/integration/targets/ndo_l3out_routed_sub_interface/tasks/main.yml
tests/integration/targets/ndo_l3out_svi_interface/aliases
tests/integration/targets/ndo_l3out_svi_interface/tasks/main.yml

fixes DCNE-430
part of https://github.com/CiscoDevNet/ansible-mso/issues/627

NDO l3out svi interface (DCNE-430)

---

plugins/module_utils/utils.py
plugins/modules/mso_schema_template_bd.py
plugins/modules/mso_schema_template_vrf_rp.py
tests/integration/targets/mso_schema_template_bd/tasks/main.yml
tests/integration/targets/mso_schema_template_vrf_rp/tasks/main.yml

Note:
Reformatted mso_schema_template_bd and mso_schema_template_vrf_rp module test files

Changed the update logic of the mso_schema_template_bd and mso_schema_template_vrf_rp modules and added additional tests (DCNE-304 DCNE-305)

---

plugins/doc_fragments/l3out_interface_ptp.py
plugins/module_utils/constants.py
plugins/module_utils/mso.py
plugins/module_utils/template.py
plugins/modules/ndo_l3out_routed_interface.py
plugins/modules/ndo_l3out_routed_sub_interface.py
tests/integration/targets/ndo_l3out_routed_interface/tasks/main.yml
tests/integration/targets/ndo_l3out_routed_sub_interface/tasks/main.yml

NDO L3out Interfaces PTP (DCNE-432)
